---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-petclinic-service-deployment-blue
  labels:
    app: spring-cloud-petclinic-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-cloud-petclinic-service
      version: green
  template:
    metadata:
      labels:
        app: spring-cloud-petclinic-service
        version: green
    spec:
      containers:
        - name: spring-cloud-petclinic-service
          image: ghcr.io/ericm48-gh-org/spring-cloud-petclinic-service:3.0.8-RELEASE
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-petclinic-service
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: spring-cloud-petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: spring-cloud-petclinic-service
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP