---
# kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spring-cloud-petclinic-service
  namespace: kommander-flux #flux-systemflux-system
spec:
  interval: 5m0s
  path: "./green"
  prune: true
  sourceRef:
    kind: GitRepository
    name: spring-cloud-petclinic-fluxcd
    namespace: kommander-flux #flux-system